// <auto-generated />
namespace HotelReservationAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _171221_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_171221_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201712202355583_171221_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
